---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: glaa-test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: glaa-test
    spec:
      containers:
      - name: glaa-test-core
        image: quay.io/ukhomeofficedigital/glaa-test:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 4000
      env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
                name: db-user
                key: supersecret          
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
                name: db-pass
                key: supersecret                