USE [master]
GO

IF NOT EXISTS (SELECT [loginname] FROM [master].[dbo].[syslogins] WHERE [name] = '$(DB_USER)')
BEGIN
    CREATE LOGIN $(DB_USER) WITH PASSWORD = $(DB_PASS);
END

ALTER LOGIN [$(DB_USER)] ENABLE
GO
GRANT CONNECT SQL TO [$(DB_USER)]
GO
DROP DATABASE IF EXISTS GLAA_Core
GO
CREATE DATABASE GLAA_Core
GO

USE [GLAA_Core]
GO

IF NOT EXISTS (SELECT [name] FROM [sys].[database_principals] WHERE [type] = 'S' AND [name] = '$(DB_USER)')
BEGIN
    CREATE USER [$(DB_USER)] FOR LOGIN [$(DB_USER)] WITH DEFAULT_SCHEMA = [dbo];
END

GRANT ALTER ON SCHEMA::dbo TO [GLAA]
GO
GRANT CREATE TABLE TO [GLAA]
GO
GRANT INSERT TO [GLAA]
GO
GRANT UPDATE TO [GLAA]
GO
GRANT DELETE TO [GLAA]
GO
GRANT SELECT ON SCHEMA::dbo TO [GLAA]
GO

