USE [master]
GO

IF NOT EXISTS (SELECT [loginname] FROM [master].[dbo].[syslogins] WHERE [name] = 'GLAA')
BEGIN
    CREATE LOGIN GLAA WITH PASSWORD = 'YouMustBeLicensedToProvideLabour';
END

ALTER LOGIN [GLAA] ENABLE
GO
GRANT CONNECT SQL TO [GLAA]
GO
DROP DATABASE IF EXISTS GLAA_Core
GO
CREATE DATABASE GLAA_Core
GO

USE [GLAA_Core]
GO

IF NOT EXISTS (SELECT [name] FROM [sys].[database_principals] WHERE [type] = 'S' AND [name] = 'GLAA')
BEGIN
    CREATE USER [GLAA] FOR LOGIN [GLAA] WITH DEFAULT_SCHEMA = [dbo];
END

GRANT ALTER ON SCHEMA::dbo TO [GLAA]
GO
GRANT CREATE TABLE TO [GLAA]
GO
GRANT INSERT TO [GLAA]
GO
GRANT UPDATE TO [GLAA]
GO
GRANT DELETE TO [GLAA]
GO
GRANT SELECT ON SCHEMA::dbo TO [GLAA]
GO

